import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Counter App";
    width: 300px;
    height: 150px;
    in-out property <int> counter: 0;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
