
import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Calculator";
    width: 300px;
    height: 400px;

    in-out property <string> display: "0";
    callback button-pressed(string);
    callback clear-pressed();
    callback equals-pressed();

    VerticalBox {
        Text {
            horizontal-alignment: right;
            font-size: 32px;
            color: #BBBBBB;
            text: root.display;
            padding: 10px;
            height: 60px;
        }
        
        Rectangle {
            background: #f000;
            border-radius: 10px;
            padding: 10px;
            VerticalBox {
                HorizontalBox {
                    spacing: 10px;
                    Button { text: "7"; clicked => { root.button-pressed("7"); } }
                    Button { text: "8"; clicked => { root.button-pressed("8"); } }
                    Button { text: "9"; clicked => { root.button-pressed("9"); } }
                    Button { text: "/"; clicked => { root.button-pressed("/"); } }
                }
                HorizontalBox {
                    spacing: 10px;
                    Button { text: "4"; clicked => { root.button-pressed("4"); } }
                    Button { text: "5"; clicked => { root.button-pressed("5"); } }
                    Button { text: "6"; clicked => { root.button-pressed("6"); } }
                    Button { text: "*"; clicked => { root.button-pressed("*"); } }
                }
                HorizontalBox {
                    spacing: 10px;
                    Button { text: "1"; clicked => { root.button-pressed("1"); } }
                    Button { text: "2"; clicked => { root.button-pressed("2"); } }
                    Button { text: "3"; clicked => { root.button-pressed("3"); } }
                    Button { text: "-"; clicked => { root.button-pressed("-"); } }
                }
                HorizontalBox {
                    spacing: 10px;
                    Button { text: "0"; clicked => { root.button-pressed("0"); } }
                    Button { text: "."; clicked => { root.button-pressed("."); } }
                    Button { text: "="; clicked => { root.equals-pressed(); } }
                    Button { text: "+"; clicked => { root.button-pressed("+"); } }
                }
                HorizontalBox {
                    spacing: 10px;
                    Rectangle {}  // Empty rectangle for flexible spacing on the left
                    Rectangle {
                        height: 40px;
                        background: #ff1111;
                        border-radius: 10px;
                        Button {
                                text: "Clear";
                                clicked => { root.clear-pressed(); }
                        }
                    }   
                    Rectangle {}  // Empty rectangle for flexible spacing on the right
                }
            }
        }
    }
}
